# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protodefs/Device.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protodefs/Device.proto", :syntax => :proto3) do
    add_message "Loc" do
      optional :x, :uint32, 1
      optional :y, :uint32, 2
    end
    add_message "Wire" do
      optional :name, :string, 1
      optional :dir, :enum, 2, "Wire.Direction"
			optional :type,:enum, 3, "Wire.Type"
      optional :start, :message, 4, "Loc"
      optional :end, :message, 5, "Loc"
      optional :R, :float, 6
      optional :C, :float, 7
      optional :unknown, :uint32, 8
      optional :switchBoxIndex, :uint32, 9
      repeated :sources, :message, 10, "Terminus"
      repeated :sinks, :message, 11, "Terminus"
		end
		add_enum "Wire.Type" do
			value :LOCAL, 0
      value :GLOBAL, 1
      value :INTERNAL, 2
			value :INTERBEL, 3
    end
    add_enum "Wire.Direction" do
      value :UNDEF, 0
      value :NORTH, 1
      value :SOUTH, 2
      value :EAST, 3
      value :WEST, 4
    end
    add_message "Pip" do
      optional :name, :string, 1
      optional :position, :message, 2, "Loc"
      repeated :inputs, :message, 3, "Wire"
      repeated :outputs, :message, 4, "Wire"
    end
    add_message "BelPin" do
      optional :name, :string, 1
      optional :type, :enum, 2, "BelPin.PinType"
      optional :wire, :message, 3, "Wire"
			optional :parent, :message, 4, "Bel"
    end
    add_enum "BelPin.PinType" do
      value :UNDEF, 0
      value :INPUT, 1
      value :OUTPUT, 2
      value :INOUT, 3
		end
		add_message "Terminus" do
			oneof :ep do
				optional :pip, :message, 1, "Pip"
        optional :bp,  :message, 2, "BelPin"
      end
    end
    add_message "Bel" do
      optional :type, :enum, 1, "Bel.BelType"
      optional :start, :message, 2, "Loc"
      optional :end, :message, 3, "Loc"
      repeated :pins, :message, 4, "BelPin"
    end
    add_enum "Bel.BelType" do
      value :UNDEF, 0
      value :IO, 1
      value :GBUF_BLOCK, 2
      value :GBUF_CTRL_BLOCK, 3
      value :EFTIO, 4
      value :EFL, 5
      value :EFT, 6
      value :MEMORY, 7
      value :MULT, 8
    end
    add_message "Device" do
      optional :name, :string, 1
      optional :speedGrade, :string, 2
      optional :dims, :message, 3, "Loc"
      repeated :bels, :message, 4, "Bel"
      repeated :pips, :message, 5, "Pip"
      repeated :wires, :message, 6, "Wire"
    end
  end
end
Terminus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Terminus").msgclass
Loc = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Loc").msgclass
Wire = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Wire").msgclass
Wire::Direction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Wire.Direction").enummodule
Wire::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Wire.Type").enummodule
Pip = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Pip").msgclass
BelPin = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BelPin").msgclass
BelPin::PinType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BelPin.PinType").enummodule
Bel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Bel").msgclass
Bel::BelType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Bel.BelType").enummodule
Device = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Device").msgclass
